<?php

namespace CustomerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerRepository extends EntityRepository
{
    
    public function findByCustomer($id)
{
    $query = $this->getEntityManager()
        ->createQuery(
            'SELECT p, c FROM CustomerBundle:Customer p
            JOIN p.note c
            WHERE p.id = :customer_id'
        )->setParameter('id', $id);

    try {
        return $query->getSingleResult();
    } catch (\Doctrine\ORM\NoResultException $e) {
        return null;
    }
}

    public function findById($id)
{
    $query = $this->getEntityManager()
        ->createQuery(
            'SELECT p, c FROM CustomerBundle:Customer p
            JOIN p.note c
            WHERE p.id = :id'
        )->setParameter('id', $id);

    try {
        return $query->getSingleResult();
    } catch (\Doctrine\ORM\NoResultException $e) {
        return null;
    }
}
}
